// ---------------------------------------------------------------------------
// Type generation — outputs a .d.ts file from a schema
// ---------------------------------------------------------------------------

import type { EnvSchema, EnvVarSchema, EnvType } from "./schema";

function tsType(schema: EnvVarSchema): string {
  const map: Record<EnvType, string> = {
    string: "string",
    number: "number",
    boolean: "boolean",
    "string[]": "string[]",
    "number[]": "number[]",
    url: "string",
    email: "string",
    port: "number",
    enum: schema.values ? schema.values.map((v) => `"${v}"`).join(" | ") : "string",
  };

  const base = map[schema.type] ?? "string";
  const hasDefault = schema.default !== undefined;
  const isOptional = schema.required === false && !hasDefault;
  return isOptional ? `${base} | undefined` : base;
}

/**
 * Generate a TypeScript declaration file for a schema.
 *
 * @example
 * ```ts
 * const dts = generateTypes({
 *   DATABASE_URL: { type: 'string', required: true },
 *   PORT: { type: 'port', default: 3000 },
 * })
 * // Outputs:
 * // declare const env: {
 * //   readonly DATABASE_URL: string;
 * //   readonly PORT: number;
 * // };
 * // export default env;
 * ```
 */
export function generateTypes(schema: EnvSchema): string {
  const lines: string[] = [
    "// Auto-generated by @tokengate/env — do not edit manually",
    "// Regenerate with: bunx tokengate generate-types",
    "",
    "declare const env: {",
  ];

  for (const [key, varSchema] of Object.entries(schema)) {
    if (varSchema.description) {
      lines.push(`  /** ${varSchema.description} */`);
    }
    lines.push(`  readonly ${key}: ${tsType(varSchema)};`);
  }

  lines.push("};", "", "export default env;", "");
  return lines.join("\n");
}

/**
 * Generate a .env.example file from a schema.
 */
export function generateExample(schema: EnvSchema): string {
  const lines: string[] = [
    "# Generated by @tokengate/env",
    "# Copy to .env and fill in your values",
    "",
  ];

  for (const [key, varSchema] of Object.entries(schema)) {
    if (varSchema.description) {
      lines.push(`# ${varSchema.description}`);
    }

    const meta: string[] = [varSchema.type];
    if (varSchema.required === false) meta.push("optional");
    if (varSchema.sensitive) meta.push("sensitive");
    if (varSchema.values) meta.push(`values: ${varSchema.values.join("|")}`);
    lines.push(`# [${meta.join(", ")}]`);

    const defaultVal = varSchema.default !== undefined ? String(varSchema.default) : "";
    lines.push(`${key}=${defaultVal}`);
    lines.push("");
  }

  return lines.join("\n");
}
